In [3]:
print("Antas")

Antas


In [4]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv('/content/imdb_text_preprocessed.csv')
print(df.info())
print(df.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   review     50000 non-null  object
 1   sentiment  50000 non-null  object
dtypes: object(2)
memory usage: 781.4+ KB
None
                                              review sentiment
0  ['one', 'reviewers', 'mention', 'watch', '1', ...  positive
1  ['wonderful', 'little', 'production', 'film', ...  positive
2  ['think', 'wonderful', 'way', 'spend', 'time',...  positive
3  ['basically', 'theres', 'family', 'little', 'b...  negative
4  ['petter', 'matteis', 'love', 'time', 'money',...  positive


In [6]:
import ast
text_str = df['review'][2]
text_list = np.array(ast.literal_eval(text_str))
print(text_list.reshape(-1, 1))

[['think']
 ['wonderful']
 ['way']
 ['spend']
 ['time']
 ['hot']
 ['summer']
 ['weekend']
 ['sit']
 ['air']
 ['condition']
 ['theater']
 ['watch']
 ['lighthearted']
 ['comedy']
 ['plot']
 ['simplistic']
 ['dialogue']
 ['witty']
 ['character']
 ['likable']
 ['even']
 ['well']
 ['bread']
 ['suspect']
 ['serial']
 ['killer']
 ['may']
 ['disappoint']
 ['realize']
 ['match']
 ['point']
 ['2']
 ['risk']
 ['addiction']
 ['think']
 ['proof']
 ['woody']
 ['allen']
 ['still']
 ['fully']
 ['control']
 ['style']
 ['many']
 ['us']
 ['grow']
 ['lovebr']
 ['id']
 ['laugh']
 ['one']
 ['woodys']
 ['comedies']
 ['years']
 ['dare']
 ['say']
 ['decade']
 ['ive']
 ['never']
 ['impress']
 ['scarlet']
 ['johanson']
 ['manage']
 ['tone']
 ['sexy']
 ['image']
 ['jump']
 ['right']
 ['average']
 ['spirit']
 ['young']
 ['womanbr']
 ['may']
 ['crown']
 ['jewel']
 ['career']
 ['wittier']
 ['devil']
 ['wear']
 ['prada']
 ['interest']
 ['superman']
 ['great']
 ['comedy']
 ['go']
 ['see']
 ['friends']]


In [7]:
#ohe impolementaion
from sklearn.preprocessing import OneHotEncoder
onehotencoder = OneHotEncoder()

sample_text_ohe = onehotencoder.fit_transform(text_list.reshape(-1, 1))
print(sample_text_ohe.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [8]:
#n-grams implementation(uni and bi)

from sklearn.feature_extraction.text import CountVectorizer
cv_uni = CountVectorizer()
sample_text_uni = cv_uni.fit_transform(text_list)
print(sample_text_uni.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [9]:
print(cv_uni.vocabulary_)

{'think': 65, 'wonderful': 77, 'way': 70, 'spend': 57, 'time': 66, 'hot': 23, 'summer': 61, 'weekend': 72, 'sit': 56, 'air': 1, 'condition': 9, 'theater': 64, 'watch': 69, 'lighthearted': 34, 'comedy': 8, 'plot': 43, 'simplistic': 55, 'dialogue': 15, 'witty': 75, 'character': 6, 'likable': 35, 'even': 17, 'well': 73, 'bread': 4, 'suspect': 63, 'serial': 53, 'killer': 32, 'may': 40, 'disappoint': 16, 'realize': 47, 'match': 39, 'point': 44, 'risk': 49, 'addiction': 0, 'proof': 46, 'woody': 78, 'allen': 2, 'still': 59, 'fully': 19, 'control': 10, 'style': 60, 'many': 38, 'us': 68, 'grow': 22, 'lovebr': 36, 'id': 24, 'laugh': 33, 'one': 42, 'woodys': 79, 'comedies': 7, 'years': 80, 'dare': 12, 'say': 50, 'decade': 13, 'ive': 28, 'never': 41, 'impress': 26, 'scarlet': 51, 'johanson': 30, 'manage': 37, 'tone': 67, 'sexy': 54, 'image': 25, 'jump': 31, 'right': 48, 'average': 3, 'spirit': 58, 'young': 81, 'womanbr': 76, 'crown': 11, 'jewel': 29, 'career': 5, 'wittier': 74, 'devil': 14, 'wear'

In [10]:
#bigram
#sample text for bi gram
def convert_to_string(text_list):
  sample_text_str = ""
  for words in text_list:
    sample_text_str = sample_text_str + " "+ words
  return sample_text_str

for i in range(0,3):
  doc_li = []
  text_str_bi = df['review'][i]
  text_list_bi = np.array(ast.literal_eval(text_str))
  sample_text_str = convert_to_string(text_list)
  doc_li.append(sample_text_str)


In [11]:
cv_bi = CountVectorizer(ngram_range=(2, 2))
sample_text_bi = cv_bi.fit_transform(doc_li)
print(sample_text_bi.toarray())

[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1]]


In [12]:
print(cv_bi.vocabulary_)

{'think wonderful': 67, 'wonderful way': 79, 'way spend': 72, 'spend time': 58, 'time hot': 68, 'hot summer': 23, 'summer weekend': 62, 'weekend sit': 74, 'sit air': 57, 'air condition': 1, 'condition theater': 10, 'theater watch': 65, 'watch lighthearted': 71, 'lighthearted comedy': 34, 'comedy plot': 9, 'plot simplistic': 44, 'simplistic dialogue': 56, 'dialogue witty': 16, 'witty character': 77, 'character likable': 6, 'likable even': 35, 'even well': 18, 'well bread': 75, 'bread suspect': 4, 'suspect serial': 64, 'serial killer': 54, 'killer may': 32, 'may disappoint': 41, 'disappoint realize': 17, 'realize match': 48, 'match point': 39, 'point risk': 45, 'risk addiction': 50, 'addiction think': 0, 'think proof': 66, 'proof woody': 47, 'woody allen': 80, 'allen still': 2, 'still fully': 60, 'fully control': 19, 'control style': 11, 'style many': 61, 'many us': 38, 'us grow': 70, 'grow lovebr': 22, 'lovebr id': 36, 'id laugh': 24, 'laugh one': 33, 'one woodys': 43, 'woodys comedies'

In [13]:
#tf-idf implementation
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()

sample_text_tfidf = tfidf.fit_transform(doc_li)
print(sample_text_tfidf.toarray())

[[0.10482848 0.10482848 0.10482848 0.10482848 0.10482848 0.10482848
  0.10482848 0.10482848 0.20965697 0.10482848 0.10482848 0.10482848
  0.10482848 0.10482848 0.10482848 0.10482848 0.10482848 0.10482848
  0.10482848 0.10482848 0.10482848 0.10482848 0.10482848 0.10482848
  0.10482848 0.10482848 0.10482848 0.10482848 0.10482848 0.10482848
  0.10482848 0.10482848 0.10482848 0.10482848 0.10482848 0.10482848
  0.10482848 0.10482848 0.10482848 0.10482848 0.20965697 0.10482848
  0.10482848 0.10482848 0.10482848 0.10482848 0.10482848 0.10482848
  0.10482848 0.10482848 0.10482848 0.10482848 0.10482848 0.10482848
  0.10482848 0.10482848 0.10482848 0.10482848 0.10482848 0.10482848
  0.10482848 0.10482848 0.10482848 0.10482848 0.10482848 0.20965697
  0.10482848 0.10482848 0.10482848 0.10482848 0.10482848 0.10482848
  0.10482848 0.10482848 0.10482848 0.10482848 0.10482848 0.10482848
  0.10482848 0.10482848 0.10482848 0.10482848]]


In [14]:
#vectorising the whole df using tf-idf

all_docs=[]
for review in df['review']:
  text_list = np.array(ast.literal_eval(review))
  sample_text_str = convert_to_string(text_list)
  all_docs.append(sample_text_str)

tfidf_all = TfidfVectorizer()
final_df_all = tfidf_all.fit_transform (all_docs)

print(final_df_all.shape)


(50000, 167587)


In [21]:
#generating a sample for 1000 rows to convert it to tfidf vector

df_10000 = df.head(10000).copy()
df_10000['tfidf_vector'] = list(final_df_all[:10000].toarray())


In [22]:
print(df_10000.head())

                                              review sentiment  \
0  ['one', 'reviewers', 'mention', 'watch', '1', ...  positive   
1  ['wonderful', 'little', 'production', 'film', ...  positive   
2  ['think', 'wonderful', 'way', 'spend', 'time',...  positive   
3  ['basically', 'theres', 'family', 'little', 'b...  negative   
4  ['petter', 'matteis', 'love', 'time', 'money',...  positive   

                                        tfidf_vector  
0  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
1  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
2  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
3  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
4  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  


In [20]:
row0 = final_df_all[0].toarray().flatten()
nonzero_idx = row0.nonzero()[0]
print([(tfidf_all.get_feature_names_out()[i], row0[i]) for i in nonzero_idx])


[('accustom', np.float64(0.0908591796062152)), ('agenda', np.float64(0.08088009383175468)), ('agreements', np.float64(0.11405597391602582)), ('appeal', np.float64(0.0550941469968932)), ('around', np.float64(0.036879956593864574)), ('audiences', np.float64(0.058961982831521896)), ('away', np.float64(0.03958771669961735)), ('awaybr', np.float64(0.080540660499188)), ('become', np.float64(0.03656863321605771)), ('bitch', np.float64(0.08029239049156082)), ('brutality', np.float64(0.08168182643097045)), ('call', np.float64(0.039610530143431195)), ('cells', np.float64(0.08495863636221156)), ('charm', np.float64(0.052615263218234336)), ('christians', np.float64(0.08315358893096646)), ('city', np.float64(0.10326608414717015)), ('class', np.float64(0.05376371050378464)), ('classic', np.float64(0.044755788654898564)), ('comfortable', np.float64(0.07524808191641658)), ('couldnt', np.float64(0.04558365460596554)), ('crook', np.float64(0.07568182150401744)), ('dare', np.float64(0.06377624819485878))

In [23]:
df_10000.to_csv('IMDB_tf-idf.csv', index=False)